export const webUpdatesDescription = [
  'PF2 Search is a browser-based lookup tool for Pathfinder 2e content stored in your local SQL Server database. From one home screen it offers five libraries — Monsters, NPCs, Spells, Feats, and Equipment — each using the same split-pane workflow: searchable filters on the left, a sortable results grid on the right, a preview card for the selected row, and a full detail modal on double-click. Monsters and NPCs both read from the joined `pf2.vwMonsterFull` view but are filtered separately (`IsNPC = 0` vs. `1`); spells, feats, and equipment query their own normalized tables with rarity, source book, trait, and type-specific filters, including full-text search for creatures and text search across summaries and raw rules text for other types.',
  'The client is React with Vite; the API is Node and Express using mssql against the `PathfinderUtil` database on SQL Server. Detail modals render stored markdown rules text, stat summaries, creature art with a zoom popout, and complete field dumps for table reference. Keyboard shortcuts support searching, moving selection in the grid, browsing records while a modal stays open, and closing overlays with Escape. Every record can link out to its Archives of Nethys page when an AoN URL is available.'
];

export const utilitiesUpdatesDescription = [
  'Pathfinder Utilities is the backend toolkit that builds and maintains the local Pathfinder 2e database this search app reads from. Python import scripts pull monsters, spells, feats, and equipment from Archives of Nethys — primarily through AoN\'s Elasticsearch search API, with an older HTML-table scraper retained for creature debugging — then normalize traits, traditions, source books, rarity, and stat blocks into SQL Server under the `pf2` schema in `PathfinderUtil`. Companion T-SQL scripts create spell, feat, and equipment tables, add foreign keys and indexes, and enable full-text search so imported content can be queried efficiently.',
  'The project is organized as a Visual Studio Python solution rather than a user-facing application: run the schema scripts, execute the appropriate `pull*.py` importers to refresh data, then run post-import SQL to finalize relationships and search indexes. That database is what powers PF2 Search at the table. Importers record AoN IDs, URLs, scrape versions, and raw HTML, text, JSON, and markdown for traceability. A separate DeepSeek folder includes adventure-module tooling for AdventureMakerByAct — creative export work rather than part of the AoN import pipeline.'
];
